// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: starmap_model.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_starmap_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{0}
}

type DataSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	ResourceName  string                 `protobuf:"bytes,5,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSource) Reset() {
	*x = DataSource{}
	mi := &file_starmap_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSource) ProtoMessage() {}

func (x *DataSource) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSource.ProtoReflect.Descriptor instead.
func (*DataSource) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{1}
}

func (x *DataSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataSource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DataSource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DataSource) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *DataSource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DataSource) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Prefix        string                 `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Topic         string                 `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_starmap_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Metadata) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Metadata) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Metadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Metadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Control struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DisableVirtualization bool                   `protobuf:"varint,1,opt,name=disableVirtualization,proto3" json:"disableVirtualization,omitempty"`
	RunDetached           bool                   `protobuf:"varint,2,opt,name=runDetached,proto3" json:"runDetached,omitempty"`
	RemoveOnStop          bool                   `protobuf:"varint,3,opt,name=removeOnStop,proto3" json:"removeOnStop,omitempty"`
	Memory                string                 `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	KernelArgs            string                 `protobuf:"bytes,5,opt,name=kernelArgs,proto3" json:"kernelArgs,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_starmap_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{3}
}

func (x *Control) GetDisableVirtualization() bool {
	if x != nil {
		return x.DisableVirtualization
	}
	return false
}

func (x *Control) GetRunDetached() bool {
	if x != nil {
		return x.RunDetached
	}
	return false
}

func (x *Control) GetRemoveOnStop() bool {
	if x != nil {
		return x.RemoveOnStop
	}
	return false
}

func (x *Control) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *Control) GetKernelArgs() string {
	if x != nil {
		return x.KernelArgs
	}
	return ""
}

type Features struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []string               `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	Ports         []string               `protobuf:"bytes,2,rep,name=ports,proto3" json:"ports,omitempty"`
	Volumes       []string               `protobuf:"bytes,3,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Targets       []string               `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	EnvVars       []string               `protobuf:"bytes,5,rep,name=envVars,proto3" json:"envVars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Features) Reset() {
	*x = Features{}
	mi := &file_starmap_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Features) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Features) ProtoMessage() {}

func (x *Features) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Features.ProtoReflect.Descriptor instead.
func (*Features) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{4}
}

func (x *Features) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *Features) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Features) GetVolumes() []string {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *Features) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Features) GetEnvVars() []string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type Links struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SoftLinks     []string               `protobuf:"bytes,1,rep,name=softLinks,proto3" json:"softLinks,omitempty"`
	HardLinks     []string               `protobuf:"bytes,2,rep,name=hardLinks,proto3" json:"hardLinks,omitempty"`
	EventLinks    []string               `protobuf:"bytes,3,rep,name=eventLinks,proto3" json:"eventLinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Links) Reset() {
	*x = Links{}
	mi := &file_starmap_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Links) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Links) ProtoMessage() {}

func (x *Links) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Links.ProtoReflect.Descriptor instead.
func (*Links) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{5}
}

func (x *Links) GetSoftLinks() []string {
	if x != nil {
		return x.SoftLinks
	}
	return nil
}

func (x *Links) GetHardLinks() []string {
	if x != nil {
		return x.HardLinks
	}
	return nil
}

func (x *Links) GetEventLinks() []string {
	if x != nil {
		return x.EventLinks
	}
	return nil
}

type StoredProcedure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Control       *Control               `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	Features      *Features              `protobuf:"bytes,3,opt,name=features,proto3" json:"features,omitempty"`
	Links         *Links                 `protobuf:"bytes,4,opt,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredProcedure) Reset() {
	*x = StoredProcedure{}
	mi := &file_starmap_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredProcedure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredProcedure) ProtoMessage() {}

func (x *StoredProcedure) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredProcedure.ProtoReflect.Descriptor instead.
func (*StoredProcedure) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{6}
}

func (x *StoredProcedure) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StoredProcedure) GetControl() *Control {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *StoredProcedure) GetFeatures() *Features {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *StoredProcedure) GetLinks() *Links {
	if x != nil {
		return x.Links
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Control       *Control               `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	Features      *Features              `protobuf:"bytes,3,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_starmap_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{7}
}

func (x *Event) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Event) GetControl() *Control {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *Event) GetFeatures() *Features {
	if x != nil {
		return x.Features
	}
	return nil
}

type EventTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Control       *Control               `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	Features      *Features              `protobuf:"bytes,3,opt,name=features,proto3" json:"features,omitempty"`
	Links         *Links                 `protobuf:"bytes,4,opt,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTrigger) Reset() {
	*x = EventTrigger{}
	mi := &file_starmap_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTrigger) ProtoMessage() {}

func (x *EventTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTrigger.ProtoReflect.Descriptor instead.
func (*EventTrigger) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{8}
}

func (x *EventTrigger) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EventTrigger) GetControl() *Control {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *EventTrigger) GetFeatures() *Features {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *EventTrigger) GetLinks() *Links {
	if x != nil {
		return x.Links
	}
	return nil
}

type Chart struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	DataSources      map[string]*DataSource      `protobuf:"bytes,1,rep,name=dataSources,proto3" json:"dataSources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StoredProcedures map[string]*StoredProcedure `protobuf:"bytes,2,rep,name=storedProcedures,proto3" json:"storedProcedures,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EventTriggers    map[string]*EventTrigger    `protobuf:"bytes,3,rep,name=eventTriggers,proto3" json:"eventTriggers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Events           map[string]*Event           `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Chart) Reset() {
	*x = Chart{}
	mi := &file_starmap_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart) ProtoMessage() {}

func (x *Chart) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart.ProtoReflect.Descriptor instead.
func (*Chart) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{9}
}

func (x *Chart) GetDataSources() map[string]*DataSource {
	if x != nil {
		return x.DataSources
	}
	return nil
}

func (x *Chart) GetStoredProcedures() map[string]*StoredProcedure {
	if x != nil {
		return x.StoredProcedures
	}
	return nil
}

func (x *Chart) GetEventTriggers() map[string]*EventTrigger {
	if x != nil {
		return x.EventTriggers
	}
	return nil
}

func (x *Chart) GetEvents() map[string]*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type MetadataChart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Maintainer    string                 `protobuf:"bytes,4,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Visibility    string                 `protobuf:"bytes,6,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Engine        string                 `protobuf:"bytes,7,opt,name=engine,proto3" json:"engine,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataChart) Reset() {
	*x = MetadataChart{}
	mi := &file_starmap_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataChart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataChart) ProtoMessage() {}

func (x *MetadataChart) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataChart.ProtoReflect.Descriptor instead.
func (*MetadataChart) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{10}
}

func (x *MetadataChart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetadataChart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataChart) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MetadataChart) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *MetadataChart) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetadataChart) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *MetadataChart) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *MetadataChart) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type StarChart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	SchemaVersion string                 `protobuf:"bytes,2,opt,name=schemaVersion,proto3" json:"schemaVersion,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *MetadataChart         `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Chart         *Chart                 `protobuf:"bytes,5,opt,name=chart,proto3" json:"chart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarChart) Reset() {
	*x = StarChart{}
	mi := &file_starmap_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarChart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarChart) ProtoMessage() {}

func (x *StarChart) ProtoReflect() protoreflect.Message {
	mi := &file_starmap_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarChart.ProtoReflect.Descriptor instead.
func (*StarChart) Descriptor() ([]byte, []int) {
	return file_starmap_model_proto_rawDescGZIP(), []int{11}
}

func (x *StarChart) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *StarChart) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *StarChart) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StarChart) GetMetadata() *MetadataChart {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StarChart) GetChart() *Chart {
	if x != nil {
		return x.Chart
	}
	return nil
}

var File_starmap_model_proto protoreflect.FileDescriptor

const file_starmap_model_proto_rawDesc = "" +
	"\n" +
	"\x13starmap_model.proto\x12\x05proto\"\x0e\n" +
	"\fEmptyMessage\"\x90\x02\n" +
	"\n" +
	"DataSource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\"\n" +
	"\fresourceName\x18\x05 \x01(\tR\fresourceName\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x125\n" +
	"\x06labels\x18\a \x03(\v2\x1d.proto.DataSource.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x02\n" +
	"\bMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05topic\x18\x05 \x01(\tR\x05topic\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x123\n" +
	"\x06labels\x18\a \x03(\v2\x1b.proto.Metadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x01\n" +
	"\aControl\x124\n" +
	"\x15disableVirtualization\x18\x01 \x01(\bR\x15disableVirtualization\x12 \n" +
	"\vrunDetached\x18\x02 \x01(\bR\vrunDetached\x12\"\n" +
	"\fremoveOnStop\x18\x03 \x01(\bR\fremoveOnStop\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\tR\x06memory\x12\x1e\n" +
	"\n" +
	"kernelArgs\x18\x05 \x01(\tR\n" +
	"kernelArgs\"\x8a\x01\n" +
	"\bFeatures\x12\x1a\n" +
	"\bnetworks\x18\x01 \x03(\tR\bnetworks\x12\x14\n" +
	"\x05ports\x18\x02 \x03(\tR\x05ports\x12\x18\n" +
	"\avolumes\x18\x03 \x03(\tR\avolumes\x12\x18\n" +
	"\atargets\x18\x04 \x03(\tR\atargets\x12\x18\n" +
	"\aenvVars\x18\x05 \x03(\tR\aenvVars\"c\n" +
	"\x05Links\x12\x1c\n" +
	"\tsoftLinks\x18\x01 \x03(\tR\tsoftLinks\x12\x1c\n" +
	"\thardLinks\x18\x02 \x03(\tR\thardLinks\x12\x1e\n" +
	"\n" +
	"eventLinks\x18\x03 \x03(\tR\n" +
	"eventLinks\"\xb9\x01\n" +
	"\x0fStoredProcedure\x12+\n" +
	"\bmetadata\x18\x01 \x01(\v2\x0f.proto.MetadataR\bmetadata\x12(\n" +
	"\acontrol\x18\x02 \x01(\v2\x0e.proto.ControlR\acontrol\x12+\n" +
	"\bfeatures\x18\x03 \x01(\v2\x0f.proto.FeaturesR\bfeatures\x12\"\n" +
	"\x05links\x18\x04 \x01(\v2\f.proto.LinksR\x05links\"\x8b\x01\n" +
	"\x05Event\x12+\n" +
	"\bmetadata\x18\x01 \x01(\v2\x0f.proto.MetadataR\bmetadata\x12(\n" +
	"\acontrol\x18\x02 \x01(\v2\x0e.proto.ControlR\acontrol\x12+\n" +
	"\bfeatures\x18\x03 \x01(\v2\x0f.proto.FeaturesR\bfeatures\"\xb6\x01\n" +
	"\fEventTrigger\x12+\n" +
	"\bmetadata\x18\x01 \x01(\v2\x0f.proto.MetadataR\bmetadata\x12(\n" +
	"\acontrol\x18\x02 \x01(\v2\x0e.proto.ControlR\acontrol\x12+\n" +
	"\bfeatures\x18\x03 \x01(\v2\x0f.proto.FeaturesR\bfeatures\x12\"\n" +
	"\x05links\x18\x04 \x01(\v2\f.proto.LinksR\x05links\"\xe1\x04\n" +
	"\x05Chart\x12?\n" +
	"\vdataSources\x18\x01 \x03(\v2\x1d.proto.Chart.DataSourcesEntryR\vdataSources\x12N\n" +
	"\x10storedProcedures\x18\x02 \x03(\v2\".proto.Chart.StoredProceduresEntryR\x10storedProcedures\x12E\n" +
	"\reventTriggers\x18\x03 \x03(\v2\x1f.proto.Chart.EventTriggersEntryR\reventTriggers\x120\n" +
	"\x06events\x18\x04 \x03(\v2\x18.proto.Chart.EventsEntryR\x06events\x1aQ\n" +
	"\x10DataSourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.DataSourceR\x05value:\x028\x01\x1a[\n" +
	"\x15StoredProceduresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.proto.StoredProcedureR\x05value:\x028\x01\x1aU\n" +
	"\x12EventTriggersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.proto.EventTriggerR\x05value:\x028\x01\x1aG\n" +
	"\vEventsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.proto.EventR\x05value:\x028\x01\"\xc0\x02\n" +
	"\rMetadataChart\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"maintainer\x18\x04 \x01(\tR\n" +
	"maintainer\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"visibility\x18\x06 \x01(\tR\n" +
	"visibility\x12\x16\n" +
	"\x06engine\x18\a \x01(\tR\x06engine\x128\n" +
	"\x06labels\x18\b \x03(\v2 .proto.MetadataChart.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\tStarChart\x12\x1e\n" +
	"\n" +
	"apiVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12$\n" +
	"\rschemaVersion\x18\x02 \x01(\tR\rschemaVersion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x120\n" +
	"\bmetadata\x18\x04 \x01(\v2\x14.proto.MetadataChartR\bmetadata\x12\"\n" +
	"\x05chart\x18\x05 \x01(\v2\f.proto.ChartR\x05chartB\x1dZ\x1bgithub.com/c12s/starmap/apib\x06proto3"

var (
	file_starmap_model_proto_rawDescOnce sync.Once
	file_starmap_model_proto_rawDescData []byte
)

func file_starmap_model_proto_rawDescGZIP() []byte {
	file_starmap_model_proto_rawDescOnce.Do(func() {
		file_starmap_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_starmap_model_proto_rawDesc), len(file_starmap_model_proto_rawDesc)))
	})
	return file_starmap_model_proto_rawDescData
}

var file_starmap_model_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_starmap_model_proto_goTypes = []any{
	(*EmptyMessage)(nil),    // 0: proto.EmptyMessage
	(*DataSource)(nil),      // 1: proto.DataSource
	(*Metadata)(nil),        // 2: proto.Metadata
	(*Control)(nil),         // 3: proto.Control
	(*Features)(nil),        // 4: proto.Features
	(*Links)(nil),           // 5: proto.Links
	(*StoredProcedure)(nil), // 6: proto.StoredProcedure
	(*Event)(nil),           // 7: proto.Event
	(*EventTrigger)(nil),    // 8: proto.EventTrigger
	(*Chart)(nil),           // 9: proto.Chart
	(*MetadataChart)(nil),   // 10: proto.MetadataChart
	(*StarChart)(nil),       // 11: proto.StarChart
	nil,                     // 12: proto.DataSource.LabelsEntry
	nil,                     // 13: proto.Metadata.LabelsEntry
	nil,                     // 14: proto.Chart.DataSourcesEntry
	nil,                     // 15: proto.Chart.StoredProceduresEntry
	nil,                     // 16: proto.Chart.EventTriggersEntry
	nil,                     // 17: proto.Chart.EventsEntry
	nil,                     // 18: proto.MetadataChart.LabelsEntry
}
var file_starmap_model_proto_depIdxs = []int32{
	12, // 0: proto.DataSource.labels:type_name -> proto.DataSource.LabelsEntry
	13, // 1: proto.Metadata.labels:type_name -> proto.Metadata.LabelsEntry
	2,  // 2: proto.StoredProcedure.metadata:type_name -> proto.Metadata
	3,  // 3: proto.StoredProcedure.control:type_name -> proto.Control
	4,  // 4: proto.StoredProcedure.features:type_name -> proto.Features
	5,  // 5: proto.StoredProcedure.links:type_name -> proto.Links
	2,  // 6: proto.Event.metadata:type_name -> proto.Metadata
	3,  // 7: proto.Event.control:type_name -> proto.Control
	4,  // 8: proto.Event.features:type_name -> proto.Features
	2,  // 9: proto.EventTrigger.metadata:type_name -> proto.Metadata
	3,  // 10: proto.EventTrigger.control:type_name -> proto.Control
	4,  // 11: proto.EventTrigger.features:type_name -> proto.Features
	5,  // 12: proto.EventTrigger.links:type_name -> proto.Links
	14, // 13: proto.Chart.dataSources:type_name -> proto.Chart.DataSourcesEntry
	15, // 14: proto.Chart.storedProcedures:type_name -> proto.Chart.StoredProceduresEntry
	16, // 15: proto.Chart.eventTriggers:type_name -> proto.Chart.EventTriggersEntry
	17, // 16: proto.Chart.events:type_name -> proto.Chart.EventsEntry
	18, // 17: proto.MetadataChart.labels:type_name -> proto.MetadataChart.LabelsEntry
	10, // 18: proto.StarChart.metadata:type_name -> proto.MetadataChart
	9,  // 19: proto.StarChart.chart:type_name -> proto.Chart
	1,  // 20: proto.Chart.DataSourcesEntry.value:type_name -> proto.DataSource
	6,  // 21: proto.Chart.StoredProceduresEntry.value:type_name -> proto.StoredProcedure
	8,  // 22: proto.Chart.EventTriggersEntry.value:type_name -> proto.EventTrigger
	7,  // 23: proto.Chart.EventsEntry.value:type_name -> proto.Event
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_starmap_model_proto_init() }
func file_starmap_model_proto_init() {
	if File_starmap_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_starmap_model_proto_rawDesc), len(file_starmap_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_starmap_model_proto_goTypes,
		DependencyIndexes: file_starmap_model_proto_depIdxs,
		MessageInfos:      file_starmap_model_proto_msgTypes,
	}.Build()
	File_starmap_model_proto = out.File
	file_starmap_model_proto_goTypes = nil
	file_starmap_model_proto_depIdxs = nil
}
